In [6]:
import numpy

In [3]:
b = np.array([1, 2, 3, 4, 5], dtype=float)

In [4]:
b

array([1., 2., 3., 4., 5.])

In [7]:
c = numpy.array([False, False, True])

In [8]:
c

array([False, False,  True])

In [9]:
b = numpy.array(1, 2, 3, 4, 5, dtype=float)

ValueError: only 2 non-keyword arguments accepted

In [10]:
f = numpy.arange(1, 2, 0.3, dtype=float)

In [11]:
f

array([1. , 1.3, 1.6, 1.9])

In [12]:
a = numpy.array([6, 3, -5])
b = numpy.array([-1, 0, 7])

In [13]:
import scipy

In [14]:
scipy.spatial.distance.cdist(b, a, metric='euclidean')

AttributeError: 'module' object has no attribute 'spatial'

In [15]:
numpy.linalg.norm(a, ord=2) - numpy.linalg.norm(b, ord=2)

1.2955324534752801

In [16]:
import numpy as np

In [17]:
e = np.arange(1, 13, 2).reshape((3, 2))

In [18]:
e

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [19]:
e = np.arange(1, 13, 2)

In [20]:
e

array([ 1,  3,  5,  7,  9, 11])

In [21]:
a = np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])

ValueError: only 2 non-keyword arguments accepted

In [22]:
d = np.ones((10, 10))

In [23]:
d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
c = np.eye((4, 5))

TypeError: 'tuple' object cannot be interpreted as an index

In [25]:
b = np.eye(2, 3)

In [26]:
b

array([[1., 0., 0.],
       [0., 1., 0.]])

In [27]:
b = np.eye(4, 4)

In [28]:
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
a = np.eye(4, 5)

In [30]:
a[[0, 3], [1, 3]]

array([0., 1.])

In [31]:
np.det(a)

AttributeError: 'module' object has no attribute 'det'

In [32]:
np.linalg.det(a)

LinAlgError: Last 2 dimensions of the array must be square