In [6]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_digits, load_breast_cancer
from sklearn.cross_validation import cross_val_score
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB

/home/toxa/anaconda3/envs/py27/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [31]:
data_breast = load_breast_cancer().data
data_digits = load_digits.data
target_breast = load_breast_cancer().target
target_digits = load_digits.target

bernoulliNB = BernoulliNB()
multinomialNB = MultinomialNB()
gaussianNB = GaussianNB()

print (data_breast)
print (data_digits)
datas = [('Breast', data_breast, target_breast), ('Digits', data_digits, target_digits)]

for name, data, target in datas:
    score_bernoulli =  cross_val_score(bernoulliNB, data, target)
    score_multinomial = cross_val_score(multinomialNB, data, target)
    score_gaussian = cross_val_score(gaussianNB, data, target)

    print (name + ' bernulli = ' + str(score_bernoulli.mean()))
    print (name + ' multinominal = ' + str(score_multinomial.mean()))
    print (name + ' gausiian = ' + str(score_gaussian.mean()))
    print ('_______')


[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
Breast bernulli = 0.6274204028589994
Breast multinominal = 0.8945790401930752
Breast gausiian = 0.9367492806089297
_______
Digits bernulli = 0.8258236507780582
Digits multinominal = 0.8708771489735053
Digits gausiian = 0.8186003803550138
_______
