In [1]:
from sklearn import cross_validation, model_selection, datasets, grid_search, linear_model, metrics, tree 
import numpy as np
import pandas as pd

def write_answer_1(auc):
    with open("answer1.txt", "w") as fout:
        fout.write(str(auc))

digits = datasets.load_digits()

print (digits.target)
print (digits.target.shape)

print (digits.data)
print (digits.data.shape)

score = model_selection.cross_val_score(tree.DecisionTreeClassifier(), digits.data, digits.target, cv=10)
print (score.mean())
write_answer_1(score.mean())

/home/toxa/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/toxa/anaconda3/lib/python3.6/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


[0 1 2 ... 8 9 8]
(1797,)
[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
(1797, 64)
0.8313915723972958


In [2]:
from sklearn import ensemble

def write_answer_2(auc):
    with open("answer2.txt", "w") as fout:
        fout.write(str(auc))

score = model_selection.cross_val_score(ensemble.BaggingClassifier(n_estimators=100), digits.data, digits.target, cv=10, n_jobs=4)
print (score.mean())
write_answer_2(score.mean())

0.9210413262369856


In [3]:
from math import sqrt

def write_answer_3(auc):
    with open("answer3.txt", "w") as fout:
        fout.write(str(auc))

d = int(sqrt(digits.data.shape[1]))
print (digits.data.shape[1])
print (d)

score = model_selection.cross_val_score(ensemble.BaggingClassifier(n_estimators=100, max_features=d), digits.data, digits.target, cv=10, n_jobs=4)
print (score.mean())
write_answer_3(score.mean())

64
8
0.9365149897521154


In [5]:
from math import sqrt

def write_answer_4(auc):
    with open("answer4.txt", "w") as fout:
        fout.write(str(auc))

def score_bagging_custom(max_feat, deep, estimators):
    return model_selection.cross_val_score(ensemble.BaggingClassifier(n_estimators=estimators, base_estimator=tree.DecisionTreeClassifier(max_features=d, max_depth=deep)), digits.data, digits.target, cv=10)

d = int(sqrt(digits.data.shape[1]))
score = score_bagging_custom(d, 10, 100)

print (score.mean())
write_answer_4(score.mean())

0.9527147008393066


In [6]:
def write_answer_5(auc):
    with open("answer5.txt", "w") as fout:
        fout.write(str(auc))
        
def score_random_forest(max_feat, deep, estimators):
    return model_selection.cross_val_score(ensemble.RandomForestClassifier(n_estimators=estimators, max_features=max_feat, max_depth=deep), digits.data, digits.target, cv=10)

d = int(sqrt(digits.data.shape[1]))
score = score_random_forest(d, 10, 100)
print (score.mean())
write_answer_5(score.mean())

0.9461111593665988


In [15]:
deep = [200]
estimators = [1, 10, 30, 40, 50, 60, 70, 80, 100]
max_features = [5]

for d in range(len(deep)):
    for e in range(len(estimators)):
        for f in range(len(max_features)):
            forest = score_random_forest(max_features[f], deep[d], estimators[e]).mean()
#             bagging = score_bagging_custom(max_features[f], deep[d], estimators[e]).mean()
            res = "deep - " + str(deep[d]) + ", n_estimators - " + str(estimators[e]) + ", max_features - " + str(max_features[f]) + ", random Forest - " + str(forest) + ", Baggin - 0";  
            print (res)

deep - 200, n_estimators - 1, max_features - 5, random Forest - 0.7144315253887876, Baggin - 0
deep - 200, n_estimators - 10, max_features - 5, random Forest - 0.9115250352769259, Baggin - 0
deep - 200, n_estimators - 30, max_features - 5, random Forest - 0.9461291395541458, Baggin - 0
deep - 200, n_estimators - 40, max_features - 5, random Forest - 0.9467092135039626, Baggin - 0
deep - 200, n_estimators - 50, max_features - 5, random Forest - 0.9517078528908762, Baggin - 0
deep - 200, n_estimators - 60, max_features - 5, random Forest - 0.9527431076765838, Baggin - 0
deep - 200, n_estimators - 70, max_features - 5, random Forest - 0.9511823180752957, Baggin - 0
deep - 200, n_estimators - 80, max_features - 5, random Forest - 0.9555462338984514, Baggin - 0
deep - 200, n_estimators - 100, max_features - 5, random Forest - 0.948349984884838, Baggin - 0
